In [1]:
import numpy as np
import math

In [2]:
x = math.inf
y = np.argmax([1,2,3,4])
y = np.argmin([1,2,3,4])
y

0

In [3]:
# class State:
#     def __init__(self):
#         color = None
        

In [4]:
#MAX = BLACK
class State:
    def __init__(self):
        self.game_board = self.intial_game_board()
        self.current_player = "MAX"
        
    def intial_game_board(self):
        initial_state = np.zeros(shape=(8,8), dtype=np.int32)
        initial_state[3,3] = 1
        initial_state[4,3] = -1
        initial_state[3,4] = -1
        initial_state[4,4] = 1
        return initial_state

In [5]:
a= State()
a.game_board[0,2]=1
a.game_board

array([[ 0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [6]:
#-1 = BLACK
# 1 = WHITE
# 0 = NADA
initial_state = np.zeros(shape=(8,8), dtype=np.int32)
initial_state[3,3] = 1
initial_state[4,3] = -1
initial_state[3,4] = -1
initial_state[4,4] = 1
initial_state

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [7]:
print(np.where(initial_state == -1))

(array([3, 4], dtype=int64), array([4, 3], dtype=int64))


In [8]:
#black = MAX
#white = MIN
# black = State()
# black.color = "black"
# black.turn = True

In [9]:
ini = State()
visited = ([2,2],[1,1])
ini.game_board[visited]=8
ini.game_board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [10]:
def player(state):
    if state.current_player == "MAX":
        return ("MIN", max_value, np.argmax)
    else:
        return ("MAX", min_value, np.argmin)

In [43]:
def change_player(state):
     if state.current_player == "MAX":
        return "MIN"
     else:
        return "MAX"

In [171]:
import copy
columns = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7}
upper_limit = 7
lower_limit = 0
def out_of_boundaries(pos):
    return pos<0 or pos>7

def move_vertical(state, value, row, column):
    result_state = state
    #down
    current_row = row + 1
    opposite_value = value*-1
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
            current_row+=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == value: #flanqueo exitoso
#             print("Vertical", row, column)
#             print("rows", int(row),current_row)
            result_state.game_board[int(row):current_row, column] = value
#             print(result_state.game_board)
    #up
    current_row = row - 1    
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
#             result_state.game_board[current_row, column] = value
            current_row-=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == value: #flanqueo exitoso
#             print("Vertical", row, column)
#             print("rows", int(row),current_row)
            result_state.game_board[current_row:int(row), column] = value
    return result_state

def move_horizontal(state, value, row, column):
    result_state = state
    opposite_value = value*-1
    #Horizontal Izquierda
    current_column = column+1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column+=1
        if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == value: 
#             print("Horizontal", row, column)
#             print("columns", int(column),current_column)
            result_state.game_board[row, int(column):current_column] = value
            
    #Horizontal Derecha
    current_column = column-1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column-=1
        if  not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == value: #flanqueo exitoso
#             print("Horizontal", row, column)
#             print("columns", int(column),current_column)
            result_state.game_board[row, current_column:int(column)] = value
    return result_state

def move_diagonal(state, value, row, column):   
    result_state = state
    opposite_value = value*-1
#     print("diag 0", result_state.game_board)
#DIAGONAL ABAJO(IZQUIRDA-DERECHA) \
    current_column = column+1
    current_row = row+1
    f = False
    temporal_state = copy.deepcopy(result_state)
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):
            temporal_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row+=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value:
            f = True
        if f:
            result_state = temporal_state
#         print("diag 1", result_state.game_board)
#             rows_flip = list(range(int(row),current_row+1))
#             cols_flip = list(range(int(column), current_column+1))
#             result_state.game_board[zip(rows_flip,cols_flip)] = value
#             print("Diagonal 1", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)
#             result_state.game_board[int(row):current_row,int(column): current_column] = value
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA)
    current_column = column+1
    current_row = row-1
    temporal_state = copy.deepcopy(result_state)
    f= False
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):        
            temporal_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            f = True
        if f:
            result_state = temporal_state
#         print("diag 2", result_state.game_board)
#             print("Diagonal 2", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)
#             rows_flip = list(range(current_row,int(row)))
#             cols_flip = list(range(int(column), current_column))
#             result_state.game_board[zip(rows_flip,cols_flip)] = value
#             result_state.game_board[current_row:int(row),int(column): current_column] = value
#DIAGONAL ABAJO(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row+1
    temporal_state = copy.deepcopy(result_state)
#     print("diag antes de 3", result_state.game_board)
    f = False
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):
            temporal_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row+=1
        print(current_row, current_column)
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value: 
#             print("FFF TRUE")
            f = True
#         print("ANTES DE ASIGNAR",result_state.game_board,temporal_state.game_board)
        if f:
            result_state = temporal_state   
#         print("diag 3", result_state.game_board)
#             print("Diagonal 3", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)
#             rows_flip = list(range(int(row),current_row))
#             cols_flip = list(range(current_column, int(column)))
            
#             print(int(row),current_row, current_column, int(column))
#             print("list for zip", rows_flip,cols_flip)
#             print(list(zip(rows_flip,cols_flip)))
#             result_state.game_board[list(zip(rows_flip,cols_flip))] = value
##DIAGONAL ARRIBA(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row-1
    f = False
    temporal_state = copy.deepcopy(result_state)
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):
            temporal_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value: 
            f = True
#             print("true")
        if f:
            result_state = temporal_state
#         print("diag 4", result_state.game_board)
#             print("Diagonal 4 ", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)           
#             rows_flip=list(range(current_row,int(row)))
#             cols_flip = list(range(current_column,int(column)))
#             result_state.game_board[zip(rows_flip,cols_flip)] = value
    return result_state
    

In [172]:
def get_possible_moves_vertical(state, pos):
    value = get_player_value(state)
    row=pos[0]
    column=pos[1]
    result_state = state
    possible_moves=[]
    #down
    current_row = row + 1
    opposite_value = value*-1
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:        
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
            current_row+=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == 0: #flanqueo exitoso            
            possible_moves.append((current_row,column))    
    #up
    current_row = row - 1    
#     print(current_row,column)
#     print("oppo", opposite_value)
#     print("curr",result_state.game_board[current_row, column] )
    if (not out_of_boundaries(current_row)) and result_state.game_board[current_row, column] == opposite_value:     
#         print("in")
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
#             result_state.game_board[current_row, column] = value
            current_row-=1            
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == 0: #flanqueo exitoso
            possible_moves.append((current_row,column))
    return possible_moves
def get_possible_moves_horizontal(state, pos):
    value = get_player_value(state)
    row=pos[0]
    column=pos[1]
    result_state = state
    possible_moves=[]  
    opposite_value = value*-1
    #Horizontal Izquierda
    current_column = column+1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column+=1
        if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == 0: 
             possible_moves.append((row,current_column))
            
    #Horizontal Derecha
    current_column = column-1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column-=1
        if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == 0: #flanqueo exitoso
            possible_moves.append((row,current_column))
    return possible_moves

def get_possible_moves_diagonal(state, pos):
    value = get_player_value(state)
    row=pos[0]
    column=pos[1]
    result_state = state
    possible_moves=[]
    opposite_value = value*-1
    #DIAGONAL ABAJO(IZQUIRDA-DERECHA) \
    current_column = column+1
    current_row = row+1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row+=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == 0: 
            possible_moves.append((current_row,current_column))
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA)
    current_column = column+1
    current_row = row-1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            result_state.game_board[int(column)+1 and int(row)-1:current_row, current_column] = value
#DIAGONAL ABAJO(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row+1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while( not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row+=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == 0: 
            possible_moves.append((current_row,current_column))
##DIAGONAL ARRIBA(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row-1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while( not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == 0: 
            possible_moves.append((current_row,current_column))
    return possible_moves

In [140]:
### def map_letters(pos):
    pos[0] = map_values[pos[0]]
    pos[1] = pos[1]+1

IndentationError: unexpected indent (Temp/ipykernel_9324/3523177645.py, line 2)

In [119]:
def get_possible_actions(state, pos):
    possible_actions=[]
    vertical_possible_actions = get_possible_moves_vertical(state, pos)
    horizontal_possible_actions = get_possible_moves_horizontal(state, pos)
    diagonal_possible_actions = get_possible_moves_diagonal(state, pos)
    if len(vertical_possible_actions)>0:        
        possible_actions.append(vertical_possible_actions)
    if len(horizontal_possible_actions)>0:
        possible_actions.append(horizontal_possible_actions)
    if len(diagonal_possible_actions)>0:
        possible_actions.append(diagonal_possible_actions)
    return possible_actions

In [100]:
a= State()
a.game_board[3,3]=1
a.game_board[2,3]=1
a.game_board[1,4]=1
a.game_board[2,4]=1
a.game_board[4,5]=1
a.game_board[1,5]=-1
a.current_player="MAX"
print(a.game_board)
print(actions(a))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1 -1  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[[(1, 3)], [(4, 2)]], [[(5, 4), (0, 4)], [(3, 2)], [(5, 6), (1, 2)]], [[(1, 3)], [(4, 6)]]]


In [265]:
map_values = {0:"A",1:"B",2:"C",3:"D",4:"E",5:"F",6:"G",7:"H"}
def actions(state):
    value = get_player_value(state)
#     print("Val",value)
#     print("state",state.game_board, value)
    pos_values_player = np.where(state.game_board == value)
    pos_values_player = list(zip(pos_values_player[0],pos_values_player[1]))
#     print(pos_values_player)
    possible_actions = []
    for pos in pos_values_player: 
        possible_actions_pos = get_possible_actions(state, pos)       
#         print(possible_actions_pos)
        if len(possible_actions_pos) > 0:    
            #0,5 -> F1           
#             print("map",list(map(lambda action: action, possible_actions_pos))) #5,4, 3,2
            possible_actions_pos = list(map(lambda action: str(map_values[action[0][1]])+str(action[0][0]+1), possible_actions_pos))
            possible_actions.append(possible_actions_pos)
    
    return possible_actions
    #print(state.game_board[pos_values_player])
    # para cada valor de su color propio 
    # buscar flanqueos posibles, si encuentra agrega a la lista de acciones posibles

def get_player_value(state):
    value = 1
    if state.current_player == "MAX":
        value = -1
    return value
def result(state, action):
#     print("state before")
#     print(state.game_board)
#     print("ac",action)
    result_state = state
    column = columns[action[0]]
    row = action[1]
    value = get_player_value(state)
    
    #para las posiciones de la matriz
    current_row = int(row)-1 
    current_column = column
    
    result_state.game_board[current_row, current_column] = value
    opposite_value = value*-1

    result_state = move_vertical(result_state, value, current_row, current_column)
    result_state = move_horizontal(result_state, value, current_row, current_column)
    result_state = move_diagonal(result_state, value, current_row, current_column)   
    return result_state

In [266]:
##### D3, E3, F5,E6, F3,C3,B3,E2
#E6, F4, C3, G4, E3, C4, C5, B4, A5, F2, F3, H4
#E6, D6, C3, F3, C5, C6, B6, B5, G2, B7,A5,H1,A6, B4, C8, B8, A8
game_state = State()
possible_moves = actions(game_state)
print(possible_moves)
while len(possible_moves) > 0:
    print(game_state.game_board)
    action = input()   
    game_state = result(game_state, action)
    game_state.current_player = change_player(game_state)
    possible_moves = actions(game_state)
    print(possible_moves)

[['E6', 'C4'], ['D3', 'F5']]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


KeyboardInterrupt: Interrupted by user

In [133]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[5,2] = -1
print(a.game_board)
result(a,"F3").game_board

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
diag 0 [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
diag antes de 3 [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
5 2
ANTES DE ASIGNAR [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]] [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [70]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board[1,4]=1
a.current_player="MIN"
print(actions(a))
result(a,"D1").game_board

[[[(4, 5)]], [[(5, 3)], [(3, 5)]], [[(2, 4)], [(4, 2)]]]


array([[ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [72]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board[2,5]=-1
a.game_board[3,5]=1
a.game_board[5,5]=1
a.game_board[4,7]=-1
a.game_board[4,6]=1
a.game_board[6,5]=-1
a.game_board[2,7]=-1
a.game_board[3,6]=1
a.game_board[5,4]=1
a.game_board[6,3]=-1

a.game_board[2,3]=-1
a.game_board[3,4]=1

a.game_board[5,6]=1
a.game_board[6,7]=-1
print(a.game_board)
result(a,"F5").game_board
#Funciona NUEVA PRUEBA VERTICAL ABAJO

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0 -1  0 -1  0 -1]
 [ 0  0  0  1  1  1  1  0]
 [ 0  0  0 -1  1  0  1 -1]
 [ 0  0  0  0  1  1  1  0]
 [ 0  0  0 -1  0 -1  0 -1]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0, -1,  0, -1],
       [ 0,  0,  0,  1, -1, -1, -1,  0],
       [ 0,  0,  0, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0, -1, -1, -1,  0],
       [ 0,  0,  0, -1,  0, -1,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [155]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board[5,3]=1
a.game_board[6,3]=1
a.game_board
result(a,"D1").game_board
#prueba de que no pasa hasta el fondo

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [21]:
a= State()
a.game_board[5,4]=1
a.game_board[6,4]=1
a.game_board
result(a,"E8").game_board
#Funciona NUEVA PRUEBA VERTICAL ARRIBA

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0]])

In [22]:
a= State()
a.game_board[5,4]=1
a.game_board[6,4]=1
a.game_board[1,4]=1
a.game_board[2,4]=1
a.game_board
result(a,"E8").game_board
#prueba no pasa hasta arriba

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0]])

In [23]:
a= State()
a.game_board[3,2]=1
a.game_board[3,1]=1
a.game_board
result(a,"A4").game_board
#Funciona NUEVA PRUEBA HORIZONTAL IZQUIERDA

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  1  1  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [159]:
a= State()
a.game_board[3,2]=1
a.game_board[3,1]=1
a.game_board[3,5]=1
a.game_board[3,6]=1
a.game_board
result(a,"A4").game_board
#Prueba que no pasa al otro lado

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  1  1  1 -1  1  1  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1,  1,  1,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [155]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board
result(a,"H5").game_board
#Funciona NUEVA PRUEBA HORIZONTAL DERECHA

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [161]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board[4,1]=1
a.game_board[4,2]=1
a.game_board
result(a,"H5").game_board

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  1  1 -1  1  1  1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  1,  1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [162]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board[4,1]=1
a.game_board[4,2]=1
a.game_board
result(a,"H5").game_board

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  1  1 -1  1  1  1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  1,  1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [24]:
a= State()
a.game_board[5,2]=1
a.game_board
result(a,"B7").game_board

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [25]:
a= State()
a.game_board[5,2]=1
a.game_board
result(a,"B7").game_board
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA) /

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [26]:
a= State()
a.game_board[5,5]=-1
a.game_board
result(a,"C3").game_board
#DIAGONAL ABAJO(IZQUIRDA-DERECHA) \

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [27]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[5,2] = -1
a.game_board
result(a,"F3").game_board
#DIAGONAL ABAJO(DERECHA-IZQUIERDA /

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [28]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[2,2] = -1
a.game_board
result(a,"F6").game_board
#DIAGONAL ARRIBA(DERECHA-IZQUIERDA)

state before
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [229]:
def cut_off(state, depth):
    return depth==max_depth

In [298]:
max_depth = 2
def min_max_cutoff(state):
    print(state.game_board)
    values = []
    p, func_value, func_arg = player(state)
    state.current_player = p
    state_actions = actions(state)
    acts = []
    print("state_actions",state_actions)
    for action in state_actions:       
        for pos in action:
            print("pos min max",pos)
            state = result(state, pos)
            v = func_value(state, -math.inf, math.inf,0)
            values.append(v)
            acts.append(pos)
        state_actions = actions(state)
    #np.func_arg(values)
    idx = func_arg(values)
    print(values)
    print("idx", idx)
    return acts[idx]

In [299]:
def terminal_test(state):
    if len(actions(state)) == 0:
        return True
    return False

def utility(state):
    utility_max = len(np.where(state == -1))
    if state.current_player == "MAX":
        return utility_max
    return 64 - utility_max

def min_value(state, alpha, beta, depth):
    state.current_player = "MIN"
    print("min_value------------", depth)
    if cut_off(state, depth):
        return utility(state)
    v = math.inf
    print(state.game_board)
    state_actions = actions(state)
    print("state_actions",state_actions)
    for a in state_actions:
        for pos in a:
            print("pos", pos)
            v = min(v, max_value(result(state, pos), alpha, beta, depth+1))
            if v<=alpha:#prunning
                return v
            beta = min(beta, v)
    print("v",v)
    return v

def max_value(state, alpha, beta, depth):
    state.current_player = "MAX"
    print("max_value------------", depth)
    if cut_off(state, depth):
        return utility(state)
    v = -math.inf
    print(state.game_board)
    state_actions = actions(state)
    print("state_actions",state_actions)
    for a in state_actions:
        for pos in a:
            print("pos", pos)
            v = max(v, min_value(result(state, pos), alpha, beta, depth+1))
            if v>= beta:
                return v
            alpha = max(alpha, v)
    print("v",v)
    return v

In [300]:
min_max_cutoff(State())

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
state_actions [['D6', 'F4'], ['E3', 'C5']]
pos min max D6
max_value------------ 0
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
state_actions [['E6', 'C4', 'C6']]
pos E6
min_value------------ 1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
state_actions [['F4', 'F6'], ['F5', 'F7'], ['F6']]
pos F4
5 3
max_value------------ 2
pos F6
max_value------------ 2
pos F5
max_value------------ 2
pos F7
max_value------------ 2
pos F6
max_value------

'D6'