In [29]:
import numpy as np
import math

In [30]:
x = math.inf
y = np.argmax([1,2,3,4])
y = np.argmin([1,2,3,4])
y

0

In [31]:
# class State:
#     def __init__(self):
#         color = None
        

In [32]:
#MAX = BLACK
class State:
    def __init__(self):
        self.game_board = self.intial_game_board()
        self.current_player = "MAX"
        
    def intial_game_board(self):
        initial_state = np.zeros(shape=(8,8), dtype=np.int32)
        initial_state[3,3] = 1
        initial_state[4,3] = -1
        initial_state[3,4] = -1
        initial_state[4,4] = 1
        return initial_state

In [33]:
a= State()
a.game_board[0,2]=1
a.game_board

array([[ 0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [34]:
#-1 = BLACK
# 1 = WHITE
# 0 = NADA
initial_state = np.zeros(shape=(8,8), dtype=np.int32)
initial_state[3,3] = 1
initial_state[4,3] = -1
initial_state[3,4] = -1
initial_state[4,4] = 1
initial_state

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [35]:
print(len(np.where(initial_state == -1)))

2


In [36]:
#black = MAX
#white = MIN
# black = State()
# black.color = "black"
# black.turn = True

In [37]:
ini = State()
visited = ([2,2],[1,1])
ini.game_board[visited]=8
ini.game_board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [38]:
def player(state):
    if state.current_player == "MAX":
        return ("MIN", max_value, np.argmax)
    else:
        return ("MAX", min_value, np.argmin)

In [93]:
columns = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7}
def actions(state):
    pass
    # para cada valor de su color propio 
    # buscar flanqueos posibles, si encuentra agrega a la lista de acciones posibles
def flip_vertically(state, row,column, value):
    result_state = state
    current_column = column
    current_row = current_row + 1
    opposite_value = value*-1
    if result_state.game_board[current_row, current_column] == opposite_value:
        while(result_state.game_board[current_row, current_column] == opposite_value):
            current_row+=1
        if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
           result_state.game_board[int(row)-1:current_row, current_column] = value
    
    return result_state
def result(state, action):
    print("state before", state.game_board)
    result_state = state
    column = columns[action[0]]
    row = action[1]
    value = 1
    if result_state.current_player == "MAX":
        value = -1
    current_row = int(row)-1
    current_column = column
    result_state.game_board[current_row, current_column] = value
    opposite_value = value*-1
  
  #  result_state= flip_vertically(result_state, row,column, value)
    #controlar LIMITES
    #vertical ABAJO
#    current_row = current_row + 1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            current_row+=1
#        if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
#           result_state.game_board[int(row)-1:current_row, current_column] = value
    #Vertical ARRIBA
#    current_row = current_row - 1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#            current_row-=1
#        if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
#          result_state.game_board[int(row)-1:current_row, current_column] = value
    #Horizontal Izquierda
#    current_column = current_column+1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#            current_column+=1
#       if result_state.game_board[current_row, current_column] == value: 
#             result_state.game_board[int(column)-1:current_row, current_column] = value
#Horizontal Derecha
    current_column = current_column-1
    if result_state.game_board[current_row, current_column] == opposite_value:
        while(result_state.game_board[current_row, current_column] == opposite_value):
            result_state.game_board[current_row, current_column] = value
            current_column-=1
        if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            result_state.game_board[int(column)-1:current_row, current_column] = value
     #current_row = current_row -2
    
    
#     current_row = int(row)-1
#     result_state.game_board[int(row)-1, column]
    #horizontal
    #diagonal    
    return result_state

In [151]:
columns = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7}
def actions(state):
    pass
def result_diagonal(state, action):
    print("state before", state.game_board)
    result_state = state
    column = columns[action[0]]
    row = action[1]
    value = 1
    if result_state.current_player == "MAX":
        value = -1
    current_row = int(row)-1
    current_column = column
    result_state.game_board[current_row, current_column] = value
    opposite_value = value*-1
#DIAGONAL ABAJO(IZQUIRDA-DERECHA) \
#    current_column = current_column+1
#    current_row = current_row+1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#            current_column+=1
#            current_row+=1
#        if result_state.game_board[current_row, current_column] == value: 
#          result_state.game_board[current_row, current_column] = value
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA)
#    current_column = current_column+1
#    current_row = current_row-1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#            current_column+=1
#            current_row-=1
#        if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
#            result_state.game_board[int(column)+1 and int(row)-1:current_row, current_column] = value
#DIAGONAL ABAJO(DERECHA-IZQUIERDA)
#    current_column = current_column-1
#    current_row = current_row+1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#            current_column-=1
#            current_row+=1
#        if result_state.game_board[current_row, current_column] == value: 
#           result_state.game_board[current_row, current_column] = value
##DIAGONAL ARRIBA(DERECHA-IZQUIERDA)
    current_column = current_column-1
    current_row = current_row-1
    if result_state.game_board[current_row, current_column] == opposite_value:
        while(result_state.game_board[current_row, current_column] == opposite_value):
            result_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row-=1
        if result_state.game_board[current_row, current_column] == value: 
           result_state.game_board[current_row, current_column] = value
    return result_state

In [78]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board
result(a,"D1").game_board
#Funciona NUEVA PRUEBA VERTICAL ABAJO

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [81]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board[5,3]=1
a.game_board[6,3]=1
a.game_board
result(a,"D1").game_board
#prueba de que no pasa hasta el fondo

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [83]:
a= State()
a.game_board[5,4]=1
a.game_board[6,4]=1
a.game_board
result(a,"E0").game_board
#Funciona NUEVA PRUEBA VERTICAL ARRIBA

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0]])

In [88]:
a= State()
a.game_board[5,4]=1
a.game_board[6,4]=1
a.game_board[1,4]=1
a.game_board[2,4]=1
a.game_board
result(a,"E8").game_board
#prueba no pasa hasta arriba

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0]])

In [91]:
a= State()
a.game_board[3,2]=1
a.game_board[3,1]=1
a.game_board
result(a,"A4").game_board
#Funciona NUEVA PRUEBA HORIZONTAL IZQUIERDA

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  1  1  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [92]:
a= State()
a.game_board[3,2]=1
a.game_board[3,1]=1
a.game_board[3,5]=1
a.game_board[3,6]=1
a.game_board
result(a,"A4").game_board
#Prueba que no pasa al otro lado

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  1  1  1 -1  1  1  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1,  1,  1,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [140]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board
result(a,"H5").game_board
#Funciona NUEVA PRUEBA HORIZONTAL DERECHA

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  1  1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [138]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board[4,1]=1
a.game_board[4,2]=1
a.game_board
result(a,"H5").game_board

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  1  1 -1  1  1  1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  1,  1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [111]:
a= State()
a.game_board[5,2]=1
a.game_board
result_diagonal(a,"B7").game_board
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA) /

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [137]:
a= State()
a.game_board[5,5]=-1
a.game_board
result_diagonal(a,"C3").game_board
#DIAGONAL ABAJO(IZQUIRDA-DERECHA) \

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [148]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[5,2] = -1
a.game_board
result_diagonal(a,"F3").game_board
#DIAGONAL ABAJO(DERECHA-IZQUIERDA /

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [152]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[2,2] = -1
a.game_board
result_diagonal(a,"F6").game_board
#DIAGONAL ARRIBA(DERECHA-IZQUIERDA)

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
def min_max_decision(state):
    values = []
    player, func_value, func_arg = player(state)
    state.current_player = player
    state_actions = actions(state)
    for action in state_actions:
        v = func_value(result(state, action))
        values.append(v)
        idx = func_arg(values)
    return state_actions[idx]

In [ ]:
def terminal_test(state):
    if len(actions(state)) == 0:
        return True
    return False

def utility(state):
    utility_max = len(np.where(state == -1))
    if state.current_player == "MAX":
        return utility_max
    return 64 - utility_max

def min_value(state):
    if terminal_test(state):
        return utility(state)
    v = math.inf
    state_actions = actions(state)
    for a in state_actions:
        v = min(v, max_value(result(state, a)))
    return v

def max_value(state):
    if terminal_test(state):
        return utility(state)
    v = -math.inf
    state_actions = actions(state)
    for a in state_actions:
        v = max(v, min_value(result(state, a)))
    return v

IndentationError: expected an indented block (Temp/ipykernel_10032/1449895688.py, line 9)