In [1]:
import numpy as np
import math

In [2]:
x = math.inf
y = np.argmax([1,2,3,4])
y = np.argmin([1,2,3,4])
y

0

In [3]:
# class State:
#     def __init__(self):
#         color = None
        

In [6]:
#MAX = BLACK
class State:
    def __init__(self):
        self.game_board = self.intial_game_board()
        self.current_player = "MAX"
        
    def intial_game_board(self):
        initial_state = np.zeros(shape=(8,8), dtype=np.int32)        
        initial_state[3,3] = 1
        initial_state[4,3] = -1
        initial_state[3,4] = -1
        initial_state[4,4] = 1
        return initial_state

In [7]:
a= State()
a.game_board[0,2]=1
a.game_board

array([[ 0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [8]:
print(np.where(initial_state == -1))

NameError: name 'initial_state' is not defined

In [9]:
ini = State()
visited = ([2,2],[1,1])
ini.game_board[visited]=8
ini.game_board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [9]:
def player(state):
    if state.current_player == "MAX":
        return ("MAX", min_value,np.argmax)
    else:
        return ("MIN", max_value, np.argmin)        

In [46]:
def change_player(state):
     if state.current_player == "MAX":
        return "MIN"
     else:
        return "MAX"

In [59]:
import copy
columns = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7}
upper_limit = 7
lower_limit = 0
def out_of_boundaries(pos):
    return pos<0 or pos>7

def not_out_of_limits(row, column):
    return not out_of_boundaries(row) and not out_of_boundaries(column)

def vertical_up_direction_update_function(row, column):
    return row+1, column

# def flanking_function_vertical_up(value, row, current_row, column, current_column, state):
# #     print("row",current_row)
#     state.game_board[int(row):current_row, column] = value
#     return state

def vertical_down_direction_update_function(row, column):
    return row-1, column

# def flanking_function_vertical_down(value, row, current_row, column, current_column, state):
# #     print("row",row)
#     state.game_board[current_row:int(row)+1, column] = value
#     return state

def horizontal_left_direction_update_function(row, column):
    return row, column-1

def horizontal_right_direction_update_function(row, column):
    return row, column+1

# def flanking_function_horizontal_left(value, row, current_row, column, current_column, state):
#     state.game_board[row, current_column:column+1] = value
#     return state

# def flanking_function_horizontal_right(value, row, current_row, column, current_column, state):
# #    print("row",row)
#     state.game_board[row, column:current_column] = value
#     return state

def diagonal_ul_direction_update_function(row, column):
    return row+1, column-1

def diagonal_ur_direction_update_function(row, column):
    return row+1, column+1

def diagonal_dl_direction_update_function(row, column):
    return row-1, column-1

def diagonal_dr_direction_update_function(row, column):
    return row-1, column+1

# def flanking_function_diagonal_ul(value, row, current_row, column, current_column, state):
#     state.game_board[row, current_column:column+1] = value
#     return state

def flank(state, value, row, column, direction_update_function):
    result_state = copy.deepcopy(state)
    opposite_value = value*-1
    successful_flanking = False
    current_row, current_column = direction_update_function(row, column)
    print(current_row, current_column)
    if not_out_of_limits(current_row, current_column) and result_state.game_board[current_row, current_column] == opposite_value:
        print(current_row, current_column)
        while(not_out_of_limits(current_row, current_column) and result_state.game_board[current_row, current_column] == opposite_value):
            result_state.game_board[current_row, current_column] = value
            current_row, current_column = direction_update_function(current_row, current_column)
            print(current_row, current_column)
        if not_out_of_limits(current_row, current_column) and result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            print("Success")
            successful_flanking = True
#             result_state = flanking_function(value, row, current_row, column, current_column, result_state)
        if successful_flanking:
            result_state.game_board[row, column] = value
            return result_state
    return state

In [80]:
a = State()
#print(flank(a,-1,5,4,vertical_down_direction_update_function).game_board)
#print(flank(a,-1,2,3,vertical_up_direction_update_function).game_board)
#print(flank(a,-1,3,2,horizontal_right_direction_update_function).game_board)
#print(flank(a,-1,4,5,horizontal_left_direction_update_function).game_board)
a.game_board[5,2]=1
a.game_board[3,2]=1
a.game_board[2,5]=1
a.game_board[4,5]=1
print(a.game_board)
#print(flank(a,-1,1,6,diagonal_ul_direction_update_function).game_board)
#print(flank(a,-1,2,1,diagonal_ur_direction_update_function).game_board)
#print(flank(a,-1,5,6,diagonal_dl_direction_update_function).game_board)
#print(flank(a,-1,6,1,diagonal_dr_direction_update_function).game_board)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  1  1 -1  0  0  0]
 [ 0  0  0 -1  1  1  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
4 5
4 5
3 4
Success
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  1  1 -1  0  0  0]
 [ 0  0  0 -1  1 -1  0  0]
 [ 0  0  1  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [10]:
import copy
columns = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7}
upper_limit = 7
lower_limit = 0
def out_of_boundaries(pos):
    return pos<0 or pos>7

def not_out_of_limits(row, column):
    return not out_of_boundaries(row) and not out_of_boundaries(column)

def vertical_up_direction_update_function(row, column):
    return row+1, column

def flanking_function_vertical_up(value, row, current_row, column, current_column, state):
    state.game_board[int(row):current_row, column] = value
    return state

def flank(state, value, row, column, direction_update_function, flanking_function):
    result_state = copy.deepcopy(state)
    opposite_value = value*-1
    current_row, current_column = direction_update_function(row, column)
    if not_out_of_limits(current_row, current_column) and result_state.game_board[current_row, current_column] == opposite_value:
        while(not_out_of_limits(current_row, current_column) and result_state.game_board[current_row, current_column] == opposite_value):
            current_row, current_column = direction_update_function(row, column)
        if not_out_of_limits(current_row, current_column) and result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            result_state = flanking_function(value, row, current_row, column, current_column, result_state)
            
def flank_vertical_down(state, value, row, column):
    result_state = state
    opposite_value = value*-1
    current_row = row + 1
    
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
            current_row+=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == value: #flanqueo exitoso
#             print("Vertical", row, column)
#             print("rows", int(row),current_row)
            result_state.game_board[int(row):current_row, column] = value

def move_vertical(state, value, row, column):
    result_state = state
    #down
    current_row = row + 1
    opposite_value = value*-1
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
            current_row+=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == value: #flanqueo exitoso
#             print("Vertical", row, column)
#             print("rows", int(row),current_row)
            result_state.game_board[int(row):current_row, column] = value
#             print(result_state.game_board)
    #up
    current_row = row - 1    
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
#             result_state.game_board[current_row, column] = value
            current_row-=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == value: #flanqueo exitoso
#             print("Vertical", row, column)
#             print("rows", int(row),current_row)
            result_state.game_board[current_row:int(row), column] = value
    return result_state

In [12]:
import copy
columns = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7}
upper_limit = 7
lower_limit = 0
def out_of_boundaries(pos):
    return pos<0 or pos>7

def move_vertical(state, value, row, column):
    result_state = state
    #down
    current_row = row + 1
    opposite_value = value*-1
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
            current_row+=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == value: #flanqueo exitoso
#             print("Vertical", row, column)
#             print("rows", int(row),current_row)
            result_state.game_board[int(row):current_row, column] = value
#             print(result_state.game_board)
    #up
    current_row = row - 1    
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
#             result_state.game_board[current_row, column] = value
            current_row-=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == value: #flanqueo exitoso
#             print("Vertical", row, column)
#             print("rows", int(row),current_row)
            result_state.game_board[current_row:int(row), column] = value
    return result_state

def move_horizontal(state, value, row, column):
    result_state = state
    opposite_value = value*-1
    #Horizontal Izquierda
    current_column = column+1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column+=1
        if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == value: 
#             print("Horizontal", row, column)
#             print("columns", int(column),current_column)
            result_state.game_board[row, int(column):current_column] = value
            
    #Horizontal Derecha
    current_column = column-1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column-=1
        if  not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == value: #flanqueo exitoso
#             print("Horizontal", row, column)
#             print("columns", int(column),current_column)
            result_state.game_board[row, current_column:int(column)] = value
    return result_state

def move_diagonal(state, value, row, column):   
    result_state = state
    opposite_value = value*-1
#     print("diag 0", result_state.game_board)
#DIAGONAL ABAJO(IZQUIRDA-DERECHA) \
    current_column = column+1
    current_row = row+1
    f = False
    temporal_state = copy.deepcopy(result_state)
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):
            temporal_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row+=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value:
            f = True
        if f:
            result_state = temporal_state
#         print("diag 1", result_state.game_board)
#             rows_flip = list(range(int(row),current_row+1))
#             cols_flip = list(range(int(column), current_column+1))
#             result_state.game_board[zip(rows_flip,cols_flip)] = value
#             print("Diagonal 1", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)
#             result_state.game_board[int(row):current_row,int(column): current_column] = value
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA)
    current_column = column+1
    current_row = row-1
    temporal_state = copy.deepcopy(result_state)
    f= False
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):        
            temporal_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            f = True
        if f:
            result_state = temporal_state
#         print("diag 2", result_state.game_board)
#             print("Diagonal 2", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)
#             rows_flip = list(range(current_row,int(row)))
#             cols_flip = list(range(int(column), current_column))
#             result_state.game_board[zip(rows_flip,cols_flip)] = value
#             result_state.game_board[current_row:int(row),int(column): current_column] = value
#DIAGONAL ABAJO(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row+1
    temporal_state = copy.deepcopy(result_state)
#     print("diag antes de 3", result_state.game_board)
    f = False
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):
            temporal_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row+=1
        print(current_row, current_column)
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value: 
#             print("FFF TRUE")
            f = True
#         print("ANTES DE ASIGNAR",result_state.game_board,temporal_state.game_board)
        if f:
            result_state = temporal_state   
#         print("diag 3", result_state.game_board)
#             print("Diagonal 3", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)
#             rows_flip = list(range(int(row),current_row))
#             cols_flip = list(range(current_column, int(column)))
            
#             print(int(row),current_row, current_column, int(column))
#             print("list for zip", rows_flip,cols_flip)
#             print(list(zip(rows_flip,cols_flip)))
#             result_state.game_board[list(zip(rows_flip,cols_flip))] = value
##DIAGONAL ARRIBA(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row-1
    f = False
    temporal_state = copy.deepcopy(result_state)
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == opposite_value):
            temporal_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and temporal_state.game_board[current_row, current_column] == value: 
            f = True
#             print("true")
        if f:
            result_state = temporal_state
#         print("diag 4", result_state.game_board)
#             print("Diagonal 4 ", row, column)
#             print("rows", int(row),current_row)
#             print("columns", int(column),current_column)           
#             rows_flip=list(range(current_row,int(row)))
#             cols_flip = list(range(current_column,int(column)))
#             result_state.game_board[zip(rows_flip,cols_flip)] = value
    return result_state
    

In [131]:
def get_possible_moves_vertical(state, pos):
    value = get_player_value(state)
    row=pos[0]
    column=pos[1]
    result_state = state
    possible_moves=[]
    #down
    current_row = row + 1
    opposite_value = value*-1
    if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value:        
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
            current_row+=1
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == 0: #flanqueo exitoso            
            possible_moves.append((current_row,column))    
    #up
    current_row = row - 1    
#     print(current_row,column)
#     print("oppo", opposite_value)
#     print("curr",result_state.game_board[current_row, column] )
    if (not out_of_boundaries(current_row)) and result_state.game_board[current_row, column] == opposite_value:     
#         print("in")
        while(not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == opposite_value):
#             result_state.game_board[current_row, column] = value
            current_row-=1            
        if not out_of_boundaries(current_row) and result_state.game_board[current_row, column] == 0: #flanqueo exitoso
            possible_moves.append((current_row,column))
    return possible_moves
def get_possible_moves_horizontal(state, pos):
    value = get_player_value(state)
    row=pos[0]
    column=pos[1]
    result_state = state
    possible_moves=[]  
    opposite_value = value*-1
    #Horizontal Izquierda
    current_column = column+1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column+=1
        if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == 0: 
             possible_moves.append((row,current_column))
            
    #Horizontal Derecha
    current_column = column-1
    if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == opposite_value):
#             result_state.game_board[row, current_column] = value
            current_column-=1
        if not out_of_boundaries(current_column) and result_state.game_board[row, current_column] == 0: #flanqueo exitoso
            possible_moves.append((row,current_column))
    return possible_moves

def get_possible_moves_diagonal(state, pos):
    value = get_player_value(state)
    row=pos[0]
    column=pos[1]
    result_state = state
    possible_moves=[]
    opposite_value = value*-1
    #DIAGONAL ABAJO(IZQUIRDA-DERECHA) \
    current_column = column+1
    current_row = row+1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row+=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == 0: 
            possible_moves.append((current_row,current_column))
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA)
    current_column = column+1
    current_row = row-1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while(not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            result_state.game_board[int(column)+1 and int(row)-1:current_row, current_column] = value
#DIAGONAL ABAJO(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row+1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while( not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row+=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == 0: 
            possible_moves.append((current_row,current_column))
##DIAGONAL ARRIBA(DERECHA-IZQUIERDA)
    current_column = column-1
    current_row = row-1
    if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value:
        while( not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == opposite_value):
#             result_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row-=1
        if not out_of_boundaries(current_column) and not out_of_boundaries(current_row) and result_state.game_board[current_row, current_column] == 0: 
            possible_moves.append((current_row,current_column))
#     print("possible_moves",possible_moves)
    return possible_moves

In [14]:
### def map_letters(pos):
    pos[0] = map_values[pos[0]]
    pos[1] = pos[1]+1

IndentationError: unexpected indent (Temp/ipykernel_22596/3523177645.py, line 2)

In [110]:
def get_possible_actions(state, pos):
    possible_actions=np.array([], np.int64)
    vertical_possible_actions = get_possible_moves_vertical(state, pos)
    horizontal_possible_actions = get_possible_moves_horizontal(state, pos)
    diagonal_possible_actions = get_possible_moves_diagonal(state, pos)
    if len(vertical_possible_actions)>0:       
        possible_actions= np.append(possible_actions,vertical_possible_actions)
#         possible_actions.append(vertical_possible_actions)
        print("Vert", vertical_possible_actions)
    if len(horizontal_possible_actions)>0:
        possible_actions= np.append(possible_actions,horizontal_possible_actions)
#         possible_actions.append(horizontal_possible_actions)
        print("hor", horizontal_possible_actions)
    if len(diagonal_possible_actions)>0:
        possible_actions= np.append(possible_actions,diagonal_possible_actions)
#         possible_actions.append(diagonal_possible_actions)
        print("diag", diagonal_possible_actions)    
    return possible_actions

In [111]:
def get_possible_actions(state, pos):
    possible_actions=[]
    vertical_possible_actions = get_possible_moves_vertical(state, pos)
    horizontal_possible_actions = get_possible_moves_horizontal(state, pos)
    diagonal_possible_actions = get_possible_moves_diagonal(state, pos)
    if len(vertical_possible_actions)>0:       
#         possible_actions= np.append(possible_actions,vertical_possible_actions)
        possible_actions.append(vertical_possible_actions)
        print("Vert", vertical_possible_actions)
    if len(horizontal_possible_actions)>0:
#         possible_actions= np.append(possible_actions,horizontal_possible_actions)
        possible_actions.append(horizontal_possible_actions)
        print("hor", horizontal_possible_actions)
    if len(diagonal_possible_actions)>0:
#         possible_actions= np.append(possible_actions,diagonal_possible_actions)
        possible_actions.append(diagonal_possible_actions)
        print("diag", diagonal_possible_actions)    
    return possible_actions

In [79]:
a= State()
a.game_board[3,3]=1
a.game_board[2,3]=1
a.game_board[1,4]=1
a.game_board[2,4]=1
a.game_board[4,5]=1
a.game_board[1,5]=-1
a.current_player="MAX"
print(a.game_board)
print(actions(a))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1 -1  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
pos_values [(1, 5), (3, 4), (4, 3)]
possible_moves [(4, 2)]
hor [(1, 3)]
diag [(4, 2)]
possible_actions_pos [[(1, 3)], [(4, 2)]]
len possible_actions_pos 2
possible_moves [(5, 6), (1, 2)]
Vert [(5, 4), (0, 4)]
hor [(3, 2)]
diag [(5, 6), (1, 2)]
possible_actions_pos [[(5, 4), (0, 4)], [(3, 2)], [(5, 6), (1, 2)]]
len possible_actions_pos 3
possible_moves []
Vert [(1, 3)]
hor [(4, 6)]
possible_actions_pos [[(1, 3)], [(4, 6)]]
len possible_actions_pos 2
[['D2', 'C5'], ['E6', 'C4', 'G6'], ['D2', 'G5']]


In [127]:
b = State()
b.game_board[3,3] = 1
b.game_board[3,4] = -1
b.game_board[4,3] = 1
b.game_board[4,4] = -1
b.game_board[5,3] = 1
b.game_board[5,4] = -1
print(b.game_board)
print(actions(b))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
pos_values [(3, 4), (4, 4), (5, 4)]
possible_moves [(5, 2)]
hor [(3, 2)]
diag [(5, 2)]
possible_actions_pos [[(3, 2)], [(5, 2)]]
possbile_action [(3, 2)]
possbile_action [(5, 2)]
possible_moves [(6, 2), (2, 2)]
hor [(4, 2)]
diag [(6, 2), (2, 2)]
possible_actions_pos [[(4, 2)], [(6, 2), (2, 2)]]
possbile_action [(4, 2)]
possbile_action [(6, 2), (2, 2)]
possible_moves [(3, 2)]
hor [(5, 2)]
diag [(3, 2)]
possible_actions_pos [[(5, 2)], [(3, 2)]]
possbile_action [(5, 2)]
possbile_action [(3, 2)]
[['C4'], ['C6'], ['C5'], ['C7', 'C3'], ['C6'], ['C4']]


In [77]:
s = []
s.append([[(3, 2)], [(5, 2)]])
s.append([[(4, 2)], [(6, 2), (2, 2)]])
s

[[[(3, 2)], [(5, 2)]], [[(4, 2)], [(6, 2), (2, 2)]]]

In [108]:
np.array([[(4, 2)], [(6, 2), (2, 2)]])

C:\Users\DELL\AppData\Local\Temp/ipykernel_22596/3760176630.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[(4, 2)], [(6, 2), (2, 2)]])


array([list([(4, 2)]), list([(6, 2), (2, 2)])], dtype=object)

In [129]:
map_values = {0:"A",1:"B",2:"C",3:"D",4:"E",5:"F",6:"G",7:"H"}
def actions(state):
    value = get_player_value(state)
#     print("Val",value)
#     print("state",state.game_board, value)
    pos_values_player = np.where(state.game_board == value)
    pos_values_player = list(zip(pos_values_player[0],pos_values_player[1]))
#     print("pos_values",pos_values_player)
    possible_actions = []
    for pos in pos_values_player: 
        possible_actions_pos = get_possible_actions(state, pos)       
#         print("possible_actions_pos",possible_actions_pos)
        if len(possible_actions_pos) > 0:    
            for possbile_action in possible_actions_pos:
#                 print("possbile_action",possbile_action)
                possible_actions_pos = list(map(lambda action: str(map_values[action[1]])+str(action[0]+1), possbile_action))
                possible_actions.append(possible_actions_pos)
    
    return possible_actions
    #print(state.game_board[pos_values_player])
    # para cada valor de su color propio 
    # buscar flanqueos posibles, si encuentra agrega a la lista de acciones posibles

def get_player_value(state):
    value = 1
    if state.current_player == "MAX":
        value = -1
    return value
def result(state, action):
#     print("state before")
#     print(state.game_board)
#     print("ac",action)
    result_state = state
    column = columns[action[0]]
    row = action[1]
    value = get_player_value(state)
    
    #para las posiciones de la matriz
    current_row = int(row)-1 
    current_column = column
    
    result_state.game_board[current_row, current_column] = value
    opposite_value = value*-1

    result_state = move_vertical(result_state, value, current_row, current_column)
    result_state = move_horizontal(result_state, value, current_row, current_column)
    result_state = move_diagonal(result_state, value, current_row, current_column)   
    return result_state

In [68]:
##### D3, E3, F5,E6, F3,C3,B3,E2
#E6, F4, C3, G4, E3, C4, C5, B4, A5, F2, F3, H4
#E6, D6, C3, F3, C5, C6, B6, B5, G2, B7,A5,H1,A6, B4, C8, B8, A8
game_state = State()
possible_moves = actions(game_state)
print(possible_moves)
while len(possible_moves) > 0:
    print(game_state.game_board)
    action = input()   
    game_state = result(game_state, action)
    game_state.current_player = change_player(game_state)
    possible_moves = actions(game_state)
    print(possible_moves)

possible_moves []
Vert [(5, 4)]
hor [(3, 2)]
possible_moves []
Vert [(2, 3)]
hor [(4, 5)]
[['E6', 'C4'], ['D3', 'F5']]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


KeyboardInterrupt: Interrupted by user

In [20]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[5,2] = -1
print(a.game_board)
result(a,"F3").game_board

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
5 2


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [21]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board[1,4]=1
a.current_player="MIN"
print(actions(a))
result(a,"D1").game_board

[['F5'], ['D6', 'F4'], ['E3', 'C5']]


array([[ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [22]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board[2,5]=-1
a.game_board[3,5]=1
a.game_board[5,5]=1
a.game_board[4,7]=-1
a.game_board[4,6]=1
a.game_board[6,5]=-1
a.game_board[2,7]=-1
a.game_board[3,6]=1
a.game_board[5,4]=1
a.game_board[6,3]=-1

a.game_board[2,3]=-1
a.game_board[3,4]=1

a.game_board[5,6]=1
a.game_board[6,7]=-1
print(a.game_board)
result(a,"F5").game_board
#Funciona NUEVA PRUEBA VERTICAL ABAJO

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0 -1  0 -1  0 -1]
 [ 0  0  0  1  1  1  1  0]
 [ 0  0  0 -1  1  0  1 -1]
 [ 0  0  0  0  1  1  1  0]
 [ 0  0  0 -1  0 -1  0 -1]
 [ 0  0  0  0  0  0  0  0]]
6 3


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0, -1,  0, -1],
       [ 0,  0,  0,  1, -1, -1, -1,  0],
       [ 0,  0,  0, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0, -1, -1, -1,  0],
       [ 0,  0,  0, -1,  0, -1,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [23]:
a= State()
a.game_board[2,3]=1
a.game_board[1,3]=1
a.game_board[5,3]=1
a.game_board[6,3]=1
a.game_board
result(a,"D1").game_board
#prueba de que no pasa hasta el fondo

array([[ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [24]:
a= State()
a.game_board[5,4]=1
a.game_board[6,4]=1
a.game_board
result(a,"E8").game_board
#Funciona NUEVA PRUEBA VERTICAL ARRIBA

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0]])

In [25]:
a= State()
a.game_board[5,4]=1
a.game_board[6,4]=1
a.game_board[1,4]=1
a.game_board[2,4]=1
a.game_board
result(a,"E8").game_board
#prueba no pasa hasta arriba

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0]])

In [26]:
a= State()
a.game_board[3,2]=1
a.game_board[3,1]=1
a.game_board
result(a,"A4").game_board
#Funciona NUEVA PRUEBA HORIZONTAL IZQUIERDA

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [27]:
a= State()
a.game_board[3,2]=1
a.game_board[3,1]=1
a.game_board[3,5]=1
a.game_board[3,6]=1
a.game_board
result(a,"A4").game_board
#Prueba que no pasa al otro lado

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1,  1,  1,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [28]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board
result(a,"H5").game_board
#Funciona NUEVA PRUEBA HORIZONTAL DERECHA

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [29]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board[4,1]=1
a.game_board[4,2]=1
a.game_board
result(a,"H5").game_board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  1,  1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [30]:
a= State()
a.game_board[4,5]=1
a.game_board[4,6]=1
a.game_board[4,1]=1
a.game_board[4,2]=1
a.game_board
result(a,"H5").game_board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  1,  1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [31]:
a= State()
a.game_board[5,2]=1
a.game_board
result(a,"B7").game_board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [32]:
a= State()
a.game_board[5,2]=1
a.game_board
result(a,"B7").game_board
#DIAGONAL ARRIBA(IZQUIERDA-DERECHA) /

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [33]:
a= State()
a.game_board[5,5]=-1
a.game_board
result(a,"C3").game_board
#DIAGONAL ABAJO(IZQUIRDA-DERECHA) \

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [34]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[5,2] = -1
a.game_board
result(a,"F3").game_board
#DIAGONAL ABAJO(DERECHA-IZQUIERDA /

5 2


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [35]:
a= State()
a.game_board[4,3] = 1
a.game_board[3,4] = 1
a.game_board[2,2] = -1
a.game_board
result(a,"F6").game_board
#DIAGONAL ARRIBA(DERECHA-IZQUIERDA)

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [40]:
max_depth = 2
def cut_off(state, depth):
    return depth==max_depth

In [142]:
def min_max_cutoff(state):
    print(state.game_board)
    values = []
    p, func_value, func_arg = player(state)
    print("player: ",p)
    state.current_player = p
    state_actions = actions(state)
    acts = []
    print("state_actions",state_actions)
    for action in state_actions:       
        for pos in action:
            print("pos min max",pos)
#             state = 
            v = func_value(result(copy.deepcopy(state), pos), -math.inf, math.inf,0)
            values.append(v)
            acts.append(pos)
            print("vvv=",v)
#         state_actions = actions(state)
    #np.func_arg(values)
    idx = func_arg(values)
    print(values)
    print("idx", idx)
    return acts[idx]

In [145]:
def terminal_test(state):
    if len(actions(state)) == 0:
        return True
    return False

def utility(state):
    utility = 0
    if state.current_player == "MAX":
        utility = len(np.where(state == -1))
    else:
        utility = len(np.where(state == 1))
    print("utility:", utility)
    return utility

def min_value(state, alpha, beta, depth):
    state.current_player = "MIN"
    print("min_value------------", depth)
    if cut_off(state, depth):
        return utility(state)
    v = math.inf
    print(state.game_board)
    state_actions = actions(state)
    print("state_actions",state_actions)
    for a in state_actions:
        for pos in a:
            print("pos", pos)
            v = min(v, max_value(result(copy.deepcopy(state), pos), alpha, beta, depth+1))
            if v<=alpha:#prunning
                return v
            beta = min(beta, v)
    print("v",v)
    return v

def max_value(state, alpha, beta, depth):
    state.current_player = "MAX"
    print("max_value------------", depth)
    if cut_off(state, depth):
        return utility(state)
    v = -math.inf
    print(state.game_board)
    state_actions = actions(state)
    print("state_actions",state_actions)
    for a in state_actions:
        for pos in a:
            print("pos", pos)
            v = max(v, min_value(result(copy.deepcopy(state), pos), alpha, beta, depth+1))
            if v>= beta:
                return v
            alpha = max(alpha, v)
    print("v",v)
    return v

In [146]:
min_max_cutoff(State())

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
player:  MAX
Vert [(5, 4)]
hor [(3, 2)]
Vert [(2, 3)]
hor [(4, 5)]
state_actions [['E6'], ['C4'], ['D3'], ['F5']]
pos min max E6
min_value------------ 0
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1 -1  0  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
Vert [(5, 3)]
hor [(3, 5)]
diag [(5, 5)]
state_actions [['D6'], ['F4'], ['F6']]
pos D6
max_value------------ 1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
hor [(3, 2)]
diag [(5, 2)]
hor [(4, 2)]
diag [(6, 2), (2, 2)]
hor [(5, 2)]
diag [(3, 

'E6'