In [2]:
import numpy as np
import math

In [3]:
x = math.inf
y = np.argmax([1,2,3,4])
y = np.argmin([1,2,3,4])
y

0

In [4]:
# class State:
#     def __init__(self):
#         color = None
        

In [5]:
#MAX = BLACK
class State:
    def __init__(self):
        self.game_board = self.intial_game_board()
        self.current_player = "MAX"
        
    def intial_game_board(self):
        initial_state = np.zeros(shape=(8,8), dtype=np.int32)
        initial_state[3,3] = 1
        initial_state[4,3] = -1
        initial_state[3,4] = -1
        initial_state[4,4] = 1
        return initial_state

In [6]:
#-1 = BLACK
# 1 = WHITE
# 0 = NADA
initial_state = np.zeros(shape=(8,8), dtype=np.int32)
initial_state[3,3] = 1
initial_state[4,3] = -1
initial_state[3,4] = -1
initial_state[4,4] = 1
initial_state

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [7]:
print(len(np.where(initial_state == -1)))

2


In [8]:
#black = MAX
#white = MIN
# black = State()
# black.color = "black"
# black.turn = True

In [9]:
ini = State()
visited = ([2,2],[1,1])
ini.game_board[visited]=8
ini.game_board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [10]:
def player(state):
    if state.current_player == "MAX":
        return ("MIN", max_value, np.argmax)
    else:
        return ("MAX", min_value, np.argmin)

In [19]:
columns = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7}
def actions(state):
    pass
    # para cada valor de su color propio 
    # buscar flanqueos posibles, si encuentra agrega a la lista de acciones posibles
def result(state, action):
    print("state before", state.game_board)
    result_state = state
    column = columns[action[0]]
    row = action[1]
    value = 1
    if result_state.current_player == "MAX":
        value = -1
    current_row = int(row)-1
    current_column = column
    result_state.game_board[current_row, current_column] = value
    opposite_value = value*-1
    #controlar LIMITES
    #vertical ARRIBA
    current_row = current_row + 1
    if result_state.game_board[current_row, current_column] == opposite_value:
        while(result_state.game_board[current_row, current_column] == opposite_value):
            current_row+=1
        if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
           result_state.game_board[int(row)-1:current_row, current_column] = value
    #Vertical ABAJO
#    current_row = current_row - 1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#           current_row-=1
#       if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
#           result_state.game_board[int(row)+1:current_row, current_column] = value
    #Horizontal Izquierda
#   current_column = current_column+1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#        while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#            current_column+=1
#       if result_state.game_board[current_row, current_column] == value: 
#             result_state.game_board[int(column)+1:current_row, current_column] = value
#Horizontal Derecha
#    current_column = current_column-1
#    if result_state.game_board[current_row, current_column] == opposite_value:
#       while(result_state.game_board[current_row, current_column] == opposite_value):
#            result_state.game_board[current_row, current_column] = value
#            current_column-=1
#       if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
#            result_state.game_board[int(column)-1:current_row, current_column] = value
#     current_row = current_row -2
    
    
#     current_row = int(row)-1
#     result_state.game_board[int(row)-1, column]
    #horizontal
    #diagonal    
    return result_state

In [12]:
def result_diagonal(state, action):
    print("state before", state.game_board)
    result_state = state
    column = columns[action[0]]
    row = action[1]
    value = 1
    if result_state.current_player == "MAX":
        value = -1
    current_row = int(row)-1
    current_column = column
    result_state.game_board[current_row, current_column] = value
    opposite_value = value*-1
#Diagonal Derecha
    current_column = current_column-1
    current_column = current_row-1
    if result_state.game_board[current_row, current_column] == opposite_value:
        while(result_state.game_board[current_row, current_column] == opposite_value):
            result_state.game_board[current_row, current_column] = value
            current_column-=1
            current_row-=1
        if result_state.game_board[current_row, current_column] == value: 
            result_state.game_board[int(column)-1:current_row, current_column] = value
#Diagonal Izquierda
    current_column = current_column+1
    current_column = current_row+1
    if result_state.game_board[current_row, current_column] == opposite_value:
        while(result_state.game_board[current_row, current_column] == opposite_value):
            result_state.game_board[current_row, current_column] = value
            current_column+=1
            current_row+=1
        if result_state.game_board[current_row, current_column] == value: #flanqueo exitoso
            result_state.game_board[int(column)+1:current_row, current_column] = value
    return result_state

In [20]:
result(State(),"D3").game_board
#Funciona

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [18]:
result(State(),"E6").game_board
#Funciona

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [16]:
result(State(),"C4").game_board
#Funciona

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [14]:
result(State(),"F5").game_board
#Funciona

state before [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
result(State(),"C3").game_board

In [ ]:
result(State(),"F6").game_board

In [17]:
def min_max_decision(state):
    values = []
    player, func_value, func_arg = player(state)
    state.current_player = player
    state_actions = actions(state)
    for action in state_actions:
        v = func_value(result(state, action))
        values.append(v)
        idx = func_arg(values)
    return state_actions[idx]

In [28]:
def terminal_test(state):
    if len(actions(state)) == 0:
        return True
    return False

def utility(state):
    utility_max = len(np.where(state == -1))
    if state.current_player == "MAX":
        return utility_max
    return 64 - utility_max

def min_value(state):
    if terminal_test(state):
        return utility(state)
    v = math.inf
    state_actions = actions(state)
    for a in state_actions:
        v = min(v, max_value(result(state, a)))
    return v

def max_value(state):
    if terminal_test(state):
        return utility(state)
    v = -math.inf
    state_actions = actions(state)
    for a in state_actions:
        v = max(v, min_value(result(state, a)))
    return v

IndentationError: expected an indented block (Temp/ipykernel_10032/1449895688.py, line 9)